with-expecter: True
dir: "{{.InterfaceDir}}/mock_{{.PackageName}}"
mockname: "{{.InterfaceName}}"
outpkg: "mock_{{.PackageName}}"
filename: "{{.InterfaceName}}.go"
include-regex: "^[A-Z].*$"
packages:
  github.com/activatedio/go-reduction: {}
  github.com/activatedio/go-reduction/internal: {}
