// Code generated by mockery v2.46.3. DO NOT EDIT.

package mock_reduction

import (
	reduction "github.com/activatedio/go-reduction"
	mock "github.com/stretchr/testify/mock"

	reflect "reflect"
)

// Builder is an autogenerated mock type for the Builder type
type Builder struct {
	mock.Mock
}

type Builder_Expecter struct {
	mock *mock.Mock
}

func (_m *Builder) EXPECT() *Builder_Expecter {
	return &Builder_Expecter{mock: &_m.Mock}
}

// State provides a mock function with given fields: t
func (_m *Builder) State(t reflect.Type) reduction.StateBuilder {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 reduction.StateBuilder
	if rf, ok := ret.Get(0).(func(reflect.Type) reduction.StateBuilder); ok {
		r0 = rf(t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reduction.StateBuilder)
		}
	}

	return r0
}

// Builder_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type Builder_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
//   - t reflect.Type
func (_e *Builder_Expecter) State(t interface{}) *Builder_State_Call {
	return &Builder_State_Call{Call: _e.mock.On("State", t)}
}

func (_c *Builder_State_Call) Run(run func(t reflect.Type)) *Builder_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(reflect.Type))
	})
	return _c
}

func (_c *Builder_State_Call) Return(_a0 reduction.StateBuilder) *Builder_State_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Builder_State_Call) RunAndReturn(run func(reflect.Type) reduction.StateBuilder) *Builder_State_Call {
	_c.Call.Return(run)
	return _c
}

// NewBuilder creates a new instance of Builder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Builder {
	mock := &Builder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
