// Code generated by mockery v2.46.3. DO NOT EDIT.

package mock_reduction

import (
	reduction "github.com/activatedio/go-reduction"
	mock "github.com/stretchr/testify/mock"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

type Factory_Expecter struct {
	mock *mock.Mock
}

func (_m *Factory) EXPECT() *Factory_Expecter {
	return &Factory_Expecter{mock: &_m.Mock}
}

// NewReduction provides a mock function with given fields:
func (_m *Factory) NewReduction() reduction.Reduction {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewReduction")
	}

	var r0 reduction.Reduction
	if rf, ok := ret.Get(0).(func() reduction.Reduction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reduction.Reduction)
		}
	}

	return r0
}

// Factory_NewReduction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewReduction'
type Factory_NewReduction_Call struct {
	*mock.Call
}

// NewReduction is a helper method to define mock.On call
func (_e *Factory_Expecter) NewReduction() *Factory_NewReduction_Call {
	return &Factory_NewReduction_Call{Call: _e.mock.On("NewReduction")}
}

func (_c *Factory_NewReduction_Call) Run(run func()) *Factory_NewReduction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Factory_NewReduction_Call) Return(_a0 reduction.Reduction) *Factory_NewReduction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Factory_NewReduction_Call) RunAndReturn(run func() reduction.Reduction) *Factory_NewReduction_Call {
	_c.Call.Return(run)
	return _c
}

// NewFactory creates a new instance of Factory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *Factory {
	mock := &Factory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
