// Code generated by mockery v2.46.3. DO NOT EDIT.

package mock_reduction

import (
	context "context"

	reduction "github.com/activatedio/go-reduction"
	mock "github.com/stretchr/testify/mock"

	reflect "reflect"
)

// Reduction is an autogenerated mock type for the Reduction type
type Reduction struct {
	mock.Mock
}

type Reduction_Expecter struct {
	mock *mock.Mock
}

func (_m *Reduction) EXPECT() *Reduction_Expecter {
	return &Reduction_Expecter{mock: &_m.Mock}
}

// Builder provides a mock function with given fields:
func (_m *Reduction) Builder() reduction.Builder {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Builder")
	}

	var r0 reduction.Builder
	if rf, ok := ret.Get(0).(func() reduction.Builder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reduction.Builder)
		}
	}

	return r0
}

// Reduction_Builder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Builder'
type Reduction_Builder_Call struct {
	*mock.Call
}

// Builder is a helper method to define mock.On call
func (_e *Reduction_Expecter) Builder() *Reduction_Builder_Call {
	return &Reduction_Builder_Call{Call: _e.mock.On("Builder")}
}

func (_c *Reduction_Builder_Call) Run(run func()) *Reduction_Builder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Reduction_Builder_Call) Return(_a0 reduction.Builder) *Reduction_Builder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Reduction_Builder_Call) RunAndReturn(run func() reduction.Builder) *Reduction_Builder_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, stateType
func (_m *Reduction) Get(ctx context.Context, stateType reflect.Type) (*reduction.GetResult, error) {
	ret := _m.Called(ctx, stateType)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *reduction.GetResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, reflect.Type) (*reduction.GetResult, error)); ok {
		return rf(ctx, stateType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, reflect.Type) *reduction.GetResult); ok {
		r0 = rf(ctx, stateType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reduction.GetResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, reflect.Type) error); ok {
		r1 = rf(ctx, stateType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reduction_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Reduction_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - stateType reflect.Type
func (_e *Reduction_Expecter) Get(ctx interface{}, stateType interface{}) *Reduction_Get_Call {
	return &Reduction_Get_Call{Call: _e.mock.On("Get", ctx, stateType)}
}

func (_c *Reduction_Get_Call) Run(run func(ctx context.Context, stateType reflect.Type)) *Reduction_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(reflect.Type))
	})
	return _c
}

func (_c *Reduction_Get_Call) Return(_a0 *reduction.GetResult, _a1 error) *Reduction_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Reduction_Get_Call) RunAndReturn(run func(context.Context, reflect.Type) (*reduction.GetResult, error)) *Reduction_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetStateDescriptors provides a mock function with given fields:
func (_m *Reduction) GetStateDescriptors() []*reduction.StateDescriptor {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStateDescriptors")
	}

	var r0 []*reduction.StateDescriptor
	if rf, ok := ret.Get(0).(func() []*reduction.StateDescriptor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*reduction.StateDescriptor)
		}
	}

	return r0
}

// Reduction_GetStateDescriptors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStateDescriptors'
type Reduction_GetStateDescriptors_Call struct {
	*mock.Call
}

// GetStateDescriptors is a helper method to define mock.On call
func (_e *Reduction_Expecter) GetStateDescriptors() *Reduction_GetStateDescriptors_Call {
	return &Reduction_GetStateDescriptors_Call{Call: _e.mock.On("GetStateDescriptors")}
}

func (_c *Reduction_GetStateDescriptors_Call) Run(run func()) *Reduction_GetStateDescriptors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Reduction_GetStateDescriptors_Call) Return(_a0 []*reduction.StateDescriptor) *Reduction_GetStateDescriptors_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Reduction_GetStateDescriptors_Call) RunAndReturn(run func() []*reduction.StateDescriptor) *Reduction_GetStateDescriptors_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, stateType, action
func (_m *Reduction) Set(ctx context.Context, stateType reflect.Type, action any) (*reduction.SetResult, error) {
	ret := _m.Called(ctx, stateType, action)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 *reduction.SetResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, reflect.Type, any) (*reduction.SetResult, error)); ok {
		return rf(ctx, stateType, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, reflect.Type, any) *reduction.SetResult); ok {
		r0 = rf(ctx, stateType, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reduction.SetResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, reflect.Type, any) error); ok {
		r1 = rf(ctx, stateType, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reduction_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Reduction_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - stateType reflect.Type
//   - action any
func (_e *Reduction_Expecter) Set(ctx interface{}, stateType interface{}, action interface{}) *Reduction_Set_Call {
	return &Reduction_Set_Call{Call: _e.mock.On("Set", ctx, stateType, action)}
}

func (_c *Reduction_Set_Call) Run(run func(ctx context.Context, stateType reflect.Type, action any)) *Reduction_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(reflect.Type), args[2].(any))
	})
	return _c
}

func (_c *Reduction_Set_Call) Return(_a0 *reduction.SetResult, _a1 error) *Reduction_Set_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Reduction_Set_Call) RunAndReturn(run func(context.Context, reflect.Type, any) (*reduction.SetResult, error)) *Reduction_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewReduction creates a new instance of Reduction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReduction(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reduction {
	mock := &Reduction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
