// Code generated by mockery v2.46.3. DO NOT EDIT.

package mock_reduction

import (
	reduction "github.com/activatedio/go-reduction"
	mock "github.com/stretchr/testify/mock"

	reflect "reflect"
)

// StateBuilder is an autogenerated mock type for the StateBuilder type
type StateBuilder struct {
	mock.Mock
}

type StateBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *StateBuilder) EXPECT() *StateBuilder_Expecter {
	return &StateBuilder_Expecter{mock: &_m.Mock}
}

// Action provides a mock function with given fields: t, reducer
func (_m *StateBuilder) Action(t reflect.Type, reducer any) reduction.StateBuilder {
	ret := _m.Called(t, reducer)

	if len(ret) == 0 {
		panic("no return value specified for Action")
	}

	var r0 reduction.StateBuilder
	if rf, ok := ret.Get(0).(func(reflect.Type, any) reduction.StateBuilder); ok {
		r0 = rf(t, reducer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reduction.StateBuilder)
		}
	}

	return r0
}

// StateBuilder_Action_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Action'
type StateBuilder_Action_Call struct {
	*mock.Call
}

// Action is a helper method to define mock.On call
//   - t reflect.Type
//   - reducer any
func (_e *StateBuilder_Expecter) Action(t interface{}, reducer interface{}) *StateBuilder_Action_Call {
	return &StateBuilder_Action_Call{Call: _e.mock.On("Action", t, reducer)}
}

func (_c *StateBuilder_Action_Call) Run(run func(t reflect.Type, reducer any)) *StateBuilder_Action_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(reflect.Type), args[1].(any))
	})
	return _c
}

func (_c *StateBuilder_Action_Call) Return(_a0 reduction.StateBuilder) *StateBuilder_Action_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateBuilder_Action_Call) RunAndReturn(run func(reflect.Type, any) reduction.StateBuilder) *StateBuilder_Action_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function with given fields: init
func (_m *StateBuilder) Init(init any) reduction.StateBuilder {
	ret := _m.Called(init)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 reduction.StateBuilder
	if rf, ok := ret.Get(0).(func(any) reduction.StateBuilder); ok {
		r0 = rf(init)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reduction.StateBuilder)
		}
	}

	return r0
}

// StateBuilder_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type StateBuilder_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - init any
func (_e *StateBuilder_Expecter) Init(init interface{}) *StateBuilder_Init_Call {
	return &StateBuilder_Init_Call{Call: _e.mock.On("Init", init)}
}

func (_c *StateBuilder_Init_Call) Run(run func(init any)) *StateBuilder_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *StateBuilder_Init_Call) Return(_a0 reduction.StateBuilder) *StateBuilder_Init_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateBuilder_Init_Call) RunAndReturn(run func(any) reduction.StateBuilder) *StateBuilder_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: init
func (_m *StateBuilder) Refresh(init any) reduction.StateBuilder {
	ret := _m.Called(init)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 reduction.StateBuilder
	if rf, ok := ret.Get(0).(func(any) reduction.StateBuilder); ok {
		r0 = rf(init)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reduction.StateBuilder)
		}
	}

	return r0
}

// StateBuilder_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type StateBuilder_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - init any
func (_e *StateBuilder_Expecter) Refresh(init interface{}) *StateBuilder_Refresh_Call {
	return &StateBuilder_Refresh_Call{Call: _e.mock.On("Refresh", init)}
}

func (_c *StateBuilder_Refresh_Call) Run(run func(init any)) *StateBuilder_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *StateBuilder_Refresh_Call) Return(_a0 reduction.StateBuilder) *StateBuilder_Refresh_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateBuilder_Refresh_Call) RunAndReturn(run func(any) reduction.StateBuilder) *StateBuilder_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewStateBuilder creates a new instance of StateBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateBuilder {
	mock := &StateBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
