// Code generated by mockery v2.46.3. DO NOT EDIT.

package mock_reduction

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// StateFactory is an autogenerated mock type for the StateFactory type
type StateFactory[S any] struct {
	mock.Mock
}

type StateFactory_Expecter[S any] struct {
	mock *mock.Mock
}

func (_m *StateFactory[S]) EXPECT() *StateFactory_Expecter[S] {
	return &StateFactory_Expecter[S]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *StateFactory[S]) Execute(ctx context.Context) (*S, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *S
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*S, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *S); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*S)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StateFactory_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type StateFactory_Execute_Call[S any] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StateFactory_Expecter[S]) Execute(ctx interface{}) *StateFactory_Execute_Call[S] {
	return &StateFactory_Execute_Call[S]{Call: _e.mock.On("Execute", ctx)}
}

func (_c *StateFactory_Execute_Call[S]) Run(run func(ctx context.Context)) *StateFactory_Execute_Call[S] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *StateFactory_Execute_Call[S]) Return(_a0 *S, _a1 error) *StateFactory_Execute_Call[S] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StateFactory_Execute_Call[S]) RunAndReturn(run func(context.Context) (*S, error)) *StateFactory_Execute_Call[S] {
	_c.Call.Return(run)
	return _c
}

// NewStateFactory creates a new instance of StateFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateFactory[S any](t interface {
	mock.TestingT
	Cleanup(func())
}) *StateFactory[S] {
	mock := &StateFactory[S]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
