// Code generated by mockery v2.45.0. DO NOT EDIT.

package mock_internal

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GetInternal is an autogenerated mock type for the GetInternal type
type GetInternal struct {
	mock.Mock
}

type GetInternal_Expecter struct {
	mock *mock.Mock
}

func (_m *GetInternal) EXPECT() *GetInternal_Expecter {
	return &GetInternal_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *GetInternal) Execute(ctx context.Context) (interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInternal_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetInternal_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GetInternal_Expecter) Execute(ctx interface{}) *GetInternal_Execute_Call {
	return &GetInternal_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *GetInternal_Execute_Call) Run(run func(ctx context.Context)) *GetInternal_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *GetInternal_Execute_Call) Return(_a0 interface{}, _a1 error) *GetInternal_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetInternal_Execute_Call) RunAndReturn(run func(context.Context) (interface{}, error)) *GetInternal_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetInternal creates a new instance of GetInternal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetInternal(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetInternal {
	mock := &GetInternal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
