// Code generated by mockery v2.46.3. DO NOT EDIT.

package mock_internal

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RefreshInternal is an autogenerated mock type for the RefreshInternal type
type RefreshInternal struct {
	mock.Mock
}

type RefreshInternal_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshInternal) EXPECT() *RefreshInternal_Expecter {
	return &RefreshInternal_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, state
func (_m *RefreshInternal) Execute(ctx context.Context, state any) (any, error) {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 any
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, any) (any, error)); ok {
		return rf(ctx, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, any) any); ok {
		r0 = rf(ctx, state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, any) error); ok {
		r1 = rf(ctx, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshInternal_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type RefreshInternal_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - state any
func (_e *RefreshInternal_Expecter) Execute(ctx interface{}, state interface{}) *RefreshInternal_Execute_Call {
	return &RefreshInternal_Execute_Call{Call: _e.mock.On("Execute", ctx, state)}
}

func (_c *RefreshInternal_Execute_Call) Run(run func(ctx context.Context, state any)) *RefreshInternal_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(any))
	})
	return _c
}

func (_c *RefreshInternal_Execute_Call) Return(_a0 any, _a1 error) *RefreshInternal_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshInternal_Execute_Call) RunAndReturn(run func(context.Context, any) (any, error)) *RefreshInternal_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefreshInternal creates a new instance of RefreshInternal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshInternal(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshInternal {
	mock := &RefreshInternal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
